export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ON_PENDING = 'REQUEST_ON_PENDING';
export const REQUEST_ON_SUCCESS = 'REQUEST_ON_SUCCESS';
export const REQUEST_ON_FAILED = 'REQUEST_ON_FAILED';
